name: Backend
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: 
      - 'backend/**'
      - '.github/workflows/backend.yml'
  pull_request:
    paths: 
      - 'backend/**'
      - '.github/workflows/backend.yml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Build
        run: go build
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '11'
      - name: Run DynamoDB Local
        run:
          wget -q https://d1ni2b6xgvw0s0.cloudfront.net/v2.x/dynamodb_local_latest.zip &&
          unzip -q dynamodb_local_latest.zip &&
          nohup java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -sharedDb -inMemory -disableTelemetry &
      - name: Wait for DynamoDB Local to start up
        run: sleep 2
      - name: Test
        run: go test
  format:
    name: Check format
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Check format
        # https://stackoverflow.com/a/42510278
        run: diff -u <(echo -n) <(gofmt -d ./)
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Lint
        run: go vet